/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Mclaren-Senna.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.401801, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089.geometry}
          material={materials.GreyBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_1.geometry}
          material={materials.Translucent}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_2.geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_3.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_4.geometry}
          material={materials.BodyPaint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_5.geometry}
          material={materials.OrangeBody}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_6.geometry}
          material={materials.BlackMetallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_7.geometry}
          material={materials.Windows}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_8.geometry}
          material={materials.Headlight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_9.geometry}
          material={materials.Top}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_10.geometry}
          material={materials.BackLighs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_11.geometry}
          material={materials.Baclight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_12.geometry}
          material={materials.Shining}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_13.geometry}
          material={materials['Back Plate']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_14.geometry}
          material={materials.Dashboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_15.geometry}
          material={materials['Red Light']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_16.geometry}
          material={materials.Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_17.geometry}
          material={materials['Seat lining']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_18.geometry}
          material={materials.Seat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_19.geometry}
          material={materials.screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_20.geometry}
          material={materials.Crbon}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_21.geometry}
          material={materials.Interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh089_22.geometry}
          material={materials.Material}
        />
        <group
          position={[1.195, -0.440325, 1.664421]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.001477, 0.001477, 0.001477]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5002.geometry}
            material={materials['wire_135006006.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5002_1.geometry}
            material={materials['wire_162162162.002']}
          />
        </group>
        <group
          position={[-1.194982, -0.440326, 1.664422]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.001477, 0.001477, 0.001477]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.uploads_files_637554_Wheel_ADV1_50.geometry}
            material={materials.wire_135006006}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.uploads_files_637554_Wheel_ADV1_50_1.geometry}
            material={materials.wire_162162162}
          />
        </group>
        <group
          position={[1.23, -0.440326, -2.136592]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.001477, 0.001477, 0.001477]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5003.geometry}
            material={materials['wire_135006006.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5003_1.geometry}
            material={materials['wire_162162162.003']}
          />
        </group>
        <group
          position={[-1.230692, -0.440325, -2.136592]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.001477, 0.001477, 0.001477]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5001.geometry}
            material={materials['wire_135006006.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.uploads_files_637554_Wheel_ADV1_5001_1.geometry}
            material={materials['wire_162162162.001']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Mclaren-Senna.glb')